# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bup < Formula
  desc "Back UP CLI written in Go"
  homepage "https://github.com/smashedr/bup"
  version "1.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smashedr/bup/releases/download/1.0.10/bup_Darwin_x86_64.tar.gz"
      sha256 "fa683aa84247b9c42cffa4cb67d3d4d0cffb7501c36d17e9cea65ecfaacb9b8e"

      def install
        bin.install "bup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smashedr/bup/releases/download/1.0.10/bup_Darwin_arm64.tar.gz"
      sha256 "609a33646f4ebb0d694df1b9d37019c2332185c7870e4e9fa4d60ccbde1d4e41"

      def install
        bin.install "bup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/bup/releases/download/1.0.10/bup_Linux_x86_64.tar.gz"
      sha256 "25d90e9f46607e194d459f18c825ee0d550119f856013b2f0d28fe96dc67d288"
      def install
        bin.install "bup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/bup/releases/download/1.0.10/bup_Linux_arm64.tar.gz"
      sha256 "40a31f2aa222ebe4b517ed003fec5a1d41594c7202c05c78365a9825f81ad9b6"
      def install
        bin.install "bup"
      end
    end
  end

  def caveats
    <<~EOS
      View the Documentation:
      https://smashedr.github.io/bup/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bup -V")
  end
end
