# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bup < Formula
  desc "Back UP CLI written in Go"
  homepage "https://smashedr.github.io/bup"
  version "1.0.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smashedr/bup/releases/download/1.0.16/bup_Darwin_x86_64.tar.gz"
      sha256 "30842438585efcbdd58ed10d1c86177e589739b2550e1ad95d6976500c44ec5e"

      def install
        bin.install "bup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smashedr/bup/releases/download/1.0.16/bup_Darwin_arm64.tar.gz"
      sha256 "6a98a0e1cda076c064df3b5726b29252dc005b8fdfd6d66590bdeac222b4180d"

      def install
        bin.install "bup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/bup/releases/download/1.0.16/bup_Linux_x86_64.tar.gz"
      sha256 "7a07d1f697ca6c883bf25cd48b72b5afde228587ca074e7e470ed15f35934771"
      def install
        bin.install "bup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/bup/releases/download/1.0.16/bup_Linux_arm64.tar.gz"
      sha256 "f75e6da6f54b70afb02715fd32f9738c1096ed4b246dc4c19a58e808f2c923ff"
      def install
        bin.install "bup"
      end
    end
  end

  def caveats
    <<~EOS
      View the Documentation:
      https://smashedr.github.io/bup/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bup -V")
  end
end
