# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bup < Formula
  desc "BackUP CLI written in Go"
  homepage "https://smashedr.github.io/bup"
  version "1.0.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smashedr/bup/releases/download/1.0.21/bup_Darwin_x86_64.tar.gz"
      sha256 "de14327d0cb909a54d9d5a550ce9f0b76e867b9534d6ed143fb45986e73548e9"

      def install
        bin.install "bup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smashedr/bup/releases/download/1.0.21/bup_Darwin_arm64.tar.gz"
      sha256 "0c9f91070aa4fa652b959b8fa2dfcd160adca67da003a8a7ff1a6073ef5ba5ff"

      def install
        bin.install "bup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/bup/releases/download/1.0.21/bup_Linux_x86_64.tar.gz"
      sha256 "fa8e6facfde69fcf529d91782eca3a4fe10b5189329f8aac7085b75c88a43d47"
      def install
        bin.install "bup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/bup/releases/download/1.0.21/bup_Linux_arm64.tar.gz"
      sha256 "32b02db31ea78f2ac868fb30717879428ca0b14b6e6e59b4ab27478e93ff74f9"
      def install
        bin.install "bup"
      end
    end
  end

  def caveats
    <<~EOS
      View the Documentation:
      https://smashedr.github.io/bup/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bup -V")
  end
end
