# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstallRelease < Formula
  desc "CLI to Install a GitHub Release"
  homepage "https://smashedr.github.io/install-release"
  version "0.0.28"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smashedr/install-release/releases/download/0.0.28/ir_Darwin_x86_64.tar.gz"
      sha256 "3d0251d09a3af614d55596f44a6997f28a1f14dca35a3ec076c743c87de726c3"

      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smashedr/install-release/releases/download/0.0.28/ir_Darwin_arm64.tar.gz"
      sha256 "afe76492f4410fd970d7dfbdcfe30c0f45b9a38136d7acb333e3a6c8ed9cbbb5"

      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.28/ir_Linux_x86_64.tar.gz"
      sha256 "e130cc6cf1505e118781c1d651798dc6e5e7d393efee2d4ff3441bb6a3297d5e"
      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.28/ir_Linux_arm64.tar.gz"
      sha256 "df7dc208fbdd71fe7535f1f48c89b7a9a6323c10f7f0d4e70438047f1edadd28"
      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
  end

  def caveats
    <<~EOS
      View the Documentation:
      https://smashedr.github.io/install-release/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/install-release -V")
  end
end
