# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstallRelease < Formula
  desc "CLI to Install a GitHub Release"
  homepage "https://smashedr.github.io/install-release"
  version "0.0.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smashedr/install-release/releases/download/0.0.23/ir_Darwin_x86_64.tar.gz"
      sha256 "a1173ba0854efde77f803137b82bf0f5c9dfe1b916d51a1dd009f931213d3bcc"

      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smashedr/install-release/releases/download/0.0.23/ir_Darwin_arm64.tar.gz"
      sha256 "c9cd5a7b5443cc91dd76558dc086bf89b46c94b12bc5a20306b84fd6a88145fd"

      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.23/ir_Linux_x86_64.tar.gz"
      sha256 "1dfdda97c3875466c8d416b45211947bc176b68237218777f3e1c3adf3147276"
      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.23/ir_Linux_arm64.tar.gz"
      sha256 "878f30b3cf709b34ed53b3f3f2c791bccce96a5f6d4eb35438c3e8ceec6f6b41"
      def install
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
  end

  def caveats
    <<~EOS
      View the Documentation:
      https://smashedr.github.io/install-release/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/install-release -V")
  end
end
