# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstallRelease < Formula
  desc "CLI to Install a GitHub Release"
  homepage "https://smashedr.github.io/install-release"
  version "0.0.30"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smashedr/install-release/releases/download/0.0.30/ir_Darwin_x86_64.tar.gz"
      sha256 "ca63839368886c67654f86b46612c5745a58d12790c1a7c6ce4d5395e898a89b"

      define_method(:install) do
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smashedr/install-release/releases/download/0.0.30/ir_Darwin_arm64.tar.gz"
      sha256 "d116958c867d211e8e92ff564476e360bfb9bb024abea767a8ddfc8d2a06dfbc"

      define_method(:install) do
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.30/ir_Linux_x86_64.tar.gz"
      sha256 "adcce0fcca4794178ed3ff6131602cc8226a10d5ebf6b79c0f91418b114b3e89"
      define_method(:install) do
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smashedr/install-release/releases/download/0.0.30/ir_Linux_arm64.tar.gz"
      sha256 "892fa4f707704baafa996e1cd84ed31190062303b8781624d38078b6d238f01b"
      define_method(:install) do
        bin.install "ir"
        bin.install_symlink "ir" => "install-release"
      end
    end
  end

  def caveats
    <<~EOS
      View the Documentation:
      https://smashedr.github.io/install-release/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/install-release -V")
  end
end
